### ISSUE TITLE
Conform to Semantic Versioning

### ISSUE THREAD

**Issue by jerryc05** [Lao-Liu233/FZYZ_JK_Grades#1]
Styling issues.

According to [Semantic Version](https://semver.org/), release version [Beta0.0.2](https://github.com/Lao-Liu233/FZYZ_JK_Grades/releases/tag/Beta0.0.2) shall be of form `0.0.2-beta1` or `0.0.2-b1` or `0.0.2-beta01`.

**Comment by Kare-Udon** [comment]
OK
